services:
    marttiphpbb.usertopiccount.update:
        class: marttiphpbb\usertopiccount\service\update
        arguments:
            - '@dbal.conn'
            - '%tables.posts%'            
            - '%tables.topics%'
            - '%tables.users%'

    marttiphpbb.usertopiccount.show_listener:
        class: marttiphpbb\usertopiccount\event\show_listener
        arguments:
            - '@auth'
            - '@config'
            - '@template'
            - '@user'
            - '@language'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }

    marttiphpbb.usertopiccount.update_listener:
        class: marttiphpbb\usertopiccount\event\update_listener
        arguments:
            - '@marttiphpbb.usertopiccount.update'
            - '@dbal.conn'
            - '%tables.posts%'
            - '%tables.topics%'
            - '%tables.users%'
        tags:
            - { name: event.listener }
